### PR TITLE
Remove unused gettext-setup dependency

### PR DESCRIPTION
**Pull request by bastelfreak**
This patch removes the dependency to gettext-setup. My understanding is
that this was a preparation to support multiple locales/languages within
the whole puppet ecosystem. I also heard that this plan was cancelled.
Also this gem has no locales. On the other side pulling gettext-setup in
raises several issues. The puppet gem starts it's locale logic if the
gem is present and that raises some errors, for example
https://tickets.puppetlabs.com/browse/MODULES-6598

Another issue is that https://github.com/puppetlabs/gettext-setup-gem
isn't maintained at all. The dependencies aren't up2date, no response
to open PRs since 1.5 years. This is also blocking the current vox
pupuli modulesync run.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hey forge team, could I get a review here? :)

**Review by caseywilliams — APPROVED** [review]
Thank you very much, @bastelfreak, and our apologies for the delay here! This looks good to me - we'll do a release later this week.

**Comment by ekohl** [comment]
I'm slightly surprised my comments from https://github.com/puppetlabs/forge-ruby/pull/91#discussion_r696503017 weren't addressed. You will have a regression where the error message is essentially duplicated since it concats.

**Comment by caseywilliams** [comment]
Hi @ekohl - I'm out today but I do plan to do some more cleanup here before we release this week - I'll be making sure your comments are addressed

**Comment by caseywilliams** [comment]
Thanks very much to @bastelfreak and @ekohl for your efforts here - version 3.2.0 has been released

**Pull request merged**
