### PR TITLE
(FORGE-360) Verify downloads using file_sha256 if available

### PR DESCRIPTION
**Pull request by scotje**
Going to test a little bit more but this should be forwards/backwards compatible.

### CODE REVIEW

**Comment by nkanderson** [comment]
Confirmed this is working testing against local Forge, pre-migration to add sha256. I'll pull and run that migration and test again.

**Comment by scotje** [comment]
Cool, there is a `rake` task to generate checksums for existing releases.

**Comment by nkanderson** [comment]
Yeah, just finished up and confirmed the sha256 check worked as well :) I'll have a couple questions over on the API PR, but this one looks good to go!

**Comment by scotje** [comment]
I'm going to make a small change to make sure it still works right when `file_sha256` is present but the value is `nil` (e.g. we have deployed the change but not run the `rake` task yet.

**Comment by nkanderson** [comment]
Perfect, that was one of my questions! I thought maybe we'd be doing something on the API deploy side to manage that, but makes sense to handle that `nil` case here.

**Pull request merged**
